UPDATE to eslint v6
adidas/js-linter-configs pull request #23
Opened 2019-11-22 13:36 UTC by RecuencoJones

- Housekeeping of dependencies
- Upgrade to eslint v6
- Update eslint-vue-plugin

2019-11-25 14:39 UTC, moelders requested changes

2019-11-25 14:39 UTC, moelders commented on package.json
> +    "lerna": "^2.11.0",
Can we move to lerna 3?

2019-11-26 10:32 UTC, RecuencoJones commented on package.json
> +    "lerna": "^2.11.0",
Done

2019-11-28 14:34 UTC, moelders approved these changes
LGTM

2019-12-02 08:15 UTC, merged