Rule updated for es5 config regarding to issue #3
adidas/js-linter-configs pull request #4
Opened 2018-09-17 07:39 UTC by bcinarli

The `no-extra-parens` rule updated as

``` js
'no-extra-parens': [ 'error', 'all', { ignoreJSX: 'multi-line', nestedBinaryExpressions: false }],
```

and `radix` rule updated as

``` js
'radix': ['error', 'as-needed'],
```

2018-09-17 08:41 UTC, RecuencoJones requested changes

2018-09-17 08:41 UTC, RecuencoJones commented on packages/eslint-config-adidas-es5/index.js
> +    'radix': ['error', 'as-needed'],
Pad array for consistency

2018-09-17 08:44 UTC, moelders commented
Fix the open issue and it LGTM.

2018-09-17 09:05 UTC, bcinarli commented on packages/eslint-config-adidas-es5/index.js
> +    'radix': ['error', 'as-needed'],
Done!

2018-09-21 07:57 UTC, moelders approved these changes
LGTM

2018-09-21 07:57 UTC, RecuencoJones approved these changes
LGTM! 🚀

2018-09-21 07:58 UTC, merged